---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAUegoQqJNpHq7e11TQ5R5q3bakbXDiW4k8jqSAUP3lP9ubSkR82gh03ACVvV8yPXOD8UND2hwaUvhU111HQHC7J1a1fr6J/38CwvTgVrPcRqpZhN9o0OG987FtbuLEZDj2IIkzznedWR3wyZ3h2MdFybPywZRKLYlrnXgsAvz4MyylyZ/YR5PgqAtEdokilofbPgYRs0wPI/sZiSq88AHdJi5859e6kFQtRoiXTqXOZntTyxOWapSIa+yziBAyCrhWDSIZwoqXYrxGQ4VBYebgw9vNyY8e4uOt8tCbr3ckMJjOhqStW/uXLTx67CT9VTudZA1UmyRSoKudjqBmVK8JBmlnpmppYTACfDDGAm6o9IZ0yPJPUAlUwmFk82J8uIG13+JFi44LQNdKaYT0OFKr9tUW1OCuGuAkfyHfhf7VP2o7G9w3S09aOXZRpxM2NshVML9MiXu5jlECXml1qTyfuxDI4ebwQtidqYcWRlcjEoyrUD8Oqo7MpBWo1fLON+P95okQU2dNbX+FgMJ//Bdnr+ZxZdAX5K9QlWgRPnn4/L5feIwvgqlWp5bKAdylziJkaymFVVhEtHBkBPkcRXl+yUPr59KpHW1m6upFwS5bR5nu62FpFLP0blOI1ecU6OOmJS40FhTQlh8QYcFqLxPr/BEmOI1Vfr5tiPOM/eNSKYOQP/wTGVU87VXoIs+iDt8nqtvT8OEKdSV0CGrnhuwV42A=
    client_secret: AgCWrcfUNF+M0GVvWlg11+5dtx/FyXhBUuaRbVHV5PqWG7jpntxZuMlCcg2sHEX6hVv6uRRFGBZiHiy2f5RuZUgWwtH0WMBDFSVBjgEfAIt0bSEuwPZWQszj4fY5VVan8zSV5uSWH1UlE3C5cYDgBewlu00r71fxJIli7eZ+c0SsnxRBoXysdxG1j3pkvW+tu+GcBFA67wtYQvSEynJbQ5/X7Rg1erMO1QsAnSUNTzrZaOsrtgTjeAqxtet5Yr6RM+PdgqAA9hY2DqDUCC5HchFWQWEHBGadv4pEOHAbZA+KrD9C+kiTlgBxvLN4PafKIHjsvG4uzSa9jXq8FZSoTdTaelPBMcQFLVjCgY7+wq9QV6ZRr8gJbo/XXcyHKPBB+EEB4gVLr6YvaBXoKzbwweWea6SkADKRNdSV5pzwiHH3ugRnOhQHL7X+/FltQppgmM1wqO4JXbGQ4xHq9Pbj/LYjPsyTOOGsnsayhw4HO5bM2gSWuel1RxTfjDt3/PlGpHfgmQRrNB+oJBYSmCyaaYa2HYP82hlgle5lAjWkNFmsjsMzHdYEjIy1X06uFJsH141SOJfz9hW6CGpnXjV0eXQzteKPB95X+PyQE5yHUdfuN9HQmnGpn34qwvorQtWePpXMSctZlTCjO53HcTKLQECzj+2uAsOBjQt5WYtj2mbtWbw3e9MhkBOgzTS2QHoX/FucoANxtpAnh226TjIN+39CCFOgub9topEA7JIpGm5+2zyo5ZWsN3rxKJV9SaGPx4CDBWkz3jvg+K2P8JeFDP9rQw==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
