---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC81Nfnwx6OalFCJ+0Tt8lZGD0KzT55Kt/+gDuRGR2klwAX9NCdbdWrSAG/RGsdSB61rRqA3Yx4Ik+83ty4IMil+YsfiaAfetXS9W+XYO5kDEZH2FO6jWWs9DEuaDOmGs5vwisGUKTS/nHeqD3lWUl9CWynPEZCSljISvKv5vTKFh/qS5yEVaPGKR7mEmjEEO6ruLn/Elnz8ydHl9DadbrL9qqohBK/vzBlO9abqvixDkbpCCAHslpfBTSad4+7W5z7Yw9kX0n8NCMeiFZFr+72m/nLoTHzzgW8agSH+xoxo9D7xEr+WI84UqNOM0XrlSm8+VChuXDgKWPJJtk/QvVaCwpOzm+BsS0ZGunuTbdoNmkrHu36UPH1P42vPjMu8DDYZZ1QcGYleEMFeQic7mGhVJDHFwbUZrpJ2BgQ8yieAa/M19j6GKhJXxHjUpt3v44iy/pdO35+tKBLBVmoRweEy0keCFMy4atDo9yaBR1h2u902nECijEF5VAz37XjqAuBcTg5xP954VYQpaxwUkKBO7wcvI3ymTXliEKxdJaOq2KJ8BBTTcUynmM5NC6NFCpPKFHfxrz2iXF0EFUGDL9oc6v0HPsfZ+PDV+8lSdnS0f98AFpjrqGSp5RuwKX1H9l1X5rYVY6dPGbHSYkl/x5KASM44F0oNSXI99LKoxZ8epQbDPBcft0WE5topERSdX3n2iHGGk8PIFx9YLM/+9vz+A==
    client_secret: AgDwE7ctbtvTQTJO9EzYVJMgjWVN+RLMSA+WauCdLJlAmZFX5+54DWDUU5ai1++hTOvoGgUxTAnN+TX4VLItyzhlYZUU2D27tT7axl3XY2DMpTddmXGepbph1ijpzB4TrMlP5/CfUso2cuFqBn33sbf+AGiYVfvox9e5uzC/pnidT7yUNMNAUyJuqx2729Hv41Nnabds4GhcUS+H+ME+2m9qNUmVxTQC6Lxb2w8+DfM248IRv6ikNS2VC3vTSUA5FqGBD9IqCGRjY4bVTb9G4eW3DnbKQH5awcI8+MWfIBmyflyvTNyQCrSNvOdJtjw5rU4TPHqFv0DbSVNyPQ55Mxgmf91lKg9I/O+KA72GZ9AIyhNqdeayP3hSPyDnF0ILL5ZI0PIFJFdYf4Ajee4uWFloUQSDjZnc+CEkvX3w/qXdAsTVTQyDmVsmlCFEzuOhcEuiRnTYGIXXz00hLTnlg5LUKMZ5vWQCD5aVMGI0cBUsO7djJjhg8w81LdVpWwguAxW4i9fGV9qHRIynXFFmrRd85bhOmxHUkMJNQPWiZkLLvDyTKh3ZbayCjnrhqJ2/jGhYZgpJE7KnOmSZXXGi+9WNBDouSJ/3zcscm/8aCvDLzzlRGfk4+JbQFbdSOGmDCM0MUpiB5W14sa60TPKx+QucBDVI1tSmqma9ByGBNTSh7zm3fYLUW7hV4ZfimC3rfR+ZUbc3c8Rq2z5TuubqN+EtK8YLTGNR9LtT+dc4WBFQY27Ch3gBnSHUbMxSfXlDHp/fpfCVoO7aBzsmCokgApTw
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
