apiVersion: v2
name: secrets-operator
description: A Helm chart for secret-operator

type: application

version: 0.1.0

dependencies:
  - name: sealed-secrets
    version: 2.17.1
    repository: https://bitnami-labs.github.io/sealed-secrets
